config/routes.rb
WCSTest::Application.routes.draw do

  resources :roi_surveys , :except => 'index'
  get '/distributors', :to=>'distributors#new'
  resources :distributors

  root to: 'home#index'
  

  get 'calculators/roi', :to=>"roi_surveys#new"

  get "home/index"
  get "home/product"
  get "home/about"
  get "home/distributor_signup"
  get "home/contact"

  

end

app/models/distributor.rb
class Distributor < ActiveRecord::Base

	validates_presence_of :company
	validates_presence_of :email
	validates_presence_of :name
	validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "is invalid" }
	validates_uniqueness_of :email
	validates_presence_of :phone
	validates_presence_of :address_1
	validates_presence_of :province
	validates_presence_of :country
	validates_presence_of :city

end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
  before_action :set_distributor, only: [:show, :edit, :update, :destroy]

  # GET /distributors
  # GET /distributors.json
  def index
    @distributors = Distributor.all
  end

  # GET /distributors/1
  # GET /distributors/1.json
  def show
  end

  # GET /distributors/new
  def new
    @distributor = Distributor.new
  end

  # GET /distributors/1/edit
  def edit
  end

  # POST /distributors
  # POST /distributors.json
  def create
    @distributor = Distributor.new(distributor_params)

    respond_to do |format|
      if @distributor.save
        ContactMailer.distributor_signup(@distributor).deliver
        format.html { redirect_to @distributor, notice: 'Distributor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @distributor }
      else
        format.html { render action: 'new' }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distributors/1
  # PATCH/PUT /distributors/1.json
  def update
    respond_to do |format|
      if @distributor.update(distributor_params)
        format.html { redirect_to @distributor, notice: 'Distributor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributors/1
  # DELETE /distributors/1.json
  def destroy
    @distributor.destroy
    respond_to do |format|
      format.html { redirect_to distributors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distributor
      @distributor = Distributor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distributor_params
      params.require(:distributor).permit(:email, :name, :phone, :address_1, :address_2, :company, :zip, :city, :province, :country)
    end
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/views/distributors/_form.html.erb
<%= form_for(@distributor) do |f| %>

  <% if @distributor.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 style="color: #3a3a3a"><%= pluralize(@distributor.errors.count, "required field") %> are incorrect or blank:</h4>

      <ul>
      <% @distributor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company, raw("Company Name<span style=\"color:red\">*</span>") %>
    <%= f.text_field :company, :class=>"form-control", :placeholder=>"My Company" %>
  </div>
  <div class="form-group">
    <%= f.label :email, raw("Your Email<span style=\"color:red\">*</span>") %>
    <%= f.text_field :email, :class=>"form-control", :placeholder=>"myname@mysite.com" %>
  </div>
  <div class="form-group">
    <%= f.label :name, raw("Your Name<span style=\"color:red\">*</span>") %>
    <%= f.text_field :name, :class=>"form-control", :placeholder=>"Firstname Lastname" %>
  </div>
  <div class="form-group">
    <%= f.label :phone, raw("Daytime Phone Number<span style=\"color:red\">*</span>") %>
    <%= f.text_field :phone, :class=>"form-control", :placeholder=>"(123) 456-7890" %>
  </div>
  <div class="form-group">
    <%= f.label :address_1, raw("Address<span style=\"color:red\">*</span>") %>
    <%= f.text_field :address_1, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address_2, "Suite/Unit #" %>
    <%= f.text_field :address_2, :class=>"form-control" %>
  </div>
  <div class="row">
    <div class="col-xs-8">
      <div class="form-group">
        <%= f.label :city, raw("City<span style=\"color:red\">*</span>") %>
        <%= f.text_field :city, :class=>"form-control" %>
      </div>      
    </div>
    <div class="col-xs-4">
      <div class="form-group">
        <%= f.label :zip, "Postal Code/Zip" %>
        <%= f.text_field :zip, :class=>"form-control" %>
      </div>  
    </div>

  </div>
  <div class="row">
    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :province, raw("Province/State<span style=\"color:red\">*</span>") %>
        <%= f.text_field :province, :class=>"form-control" %>
      </div>      
    </div>
    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :country, raw("Country<span style=\"color:red\">*</span>") %>
        <%= f.text_field :country, :class=>"form-control" %>
      </div>  
    </div>

  </div>
    

  <div class="actions clearfix">
    <%= f.submit "Sign Up", :class=>"btn btn-primary btn-lg pull-right" %>

  </div>

<% end %>

app/views/distributors/index.html.erb
<h1>Listing distributors</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>Company</th>
      <th>Zip</th>
      <th>Province</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @distributors.each do |distributor| %>
      <tr>
        <td><%= distributor.email %></td>
        <td><%= distributor.name %></td>
        <td><%= distributor.phone %></td>
        <td><%= distributor.address_1 %></td>
        <td><%= distributor.address_2 %></td>
        <td><%= distributor.company %></td>
        <td><%= distributor.zip %></td>
        <td><%= distributor.province %></td>
        <td><%= distributor.country %></td>
        <td><%= link_to 'Show', distributor %></td>
        <td><%= link_to 'Edit', edit_distributor_path(distributor) %></td>
        <td><%= link_to 'Destroy', distributor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distributor', new_distributor_path %>

app/views/distributors/new.html.erb
<% content_for :title => 'Become A Distributor' %>
<div id="distributors">
	<header>
		<div id="background"
			data-0="-ms-transform: translate(0,-100px);-moz-transform: translate(0,-100px);-webkit-transform: translate(0,-100px);transform: translate(0,-100px);" data-200="-ms-transform: translate(0,-50px);-moz-transform: translate(0,-50px);-webkit-transform: translate(0,-50px);transform: translate(0,-50px);"

		></div>
		<div id="map-cover">
			<h1 class="center">Become a SYNQ Distributor</h1>

			<ul class="header-subnav">
				<li><a class="active" href="#SignUp">Sign Up</a></li>
				
				<li><a href="#FAQ">FAQ</a></li>
			</ul>
		</div>
		<div class="back-wrap whoosh-left">
			<%= link_to raw("<i class=\"fa fa-arrow-left\"></i>"), root_url, :class=>"btn btn-round btn-default" %>
		</div>
		
	</header>
	<div class="container" style="margin-top: 50px;">
		<div class="row">
			<div class="col-md-6" id="SignUp">
					
				<div class="panel padded">
					
					<h1 class="center">Sign Up</h1>
					<p class="lead light">Fill out the form below and we will contact you within 2 business days.</p>
					<%= render 'distributors/form' %>
			
				</div>
				

			</div>
			<div class="col-md-6" id="faq">
<center>Any questions? <a href="mailto: contact@synqtech.com">Contact us now!</a></center>

				<!-- <h1 class="center">FAQ</h1>
				<p class="lead light">Frequently asked questions.</p>

				 -->

				<!-- <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
				  <div class="panel panel-default">
				    <div class="panel-heading" role="tab" id="headingOne">
				      <h4 class="panel-title">
				        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
				          How does SYNQ Cover Warranty?
				        </a>
				      </h4>
				    </div>
				    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
				      <div class="panel-body">
				        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
				      </div>
				    </div>
				  </div>
				  <div class="panel panel-default">
				    <div class="panel-heading" role="tab" id="headingTwo">
				      <h4 class="panel-title">
				        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
				          If I am looking for dimensions, specifications or need technical product information, who I should contact?
				        </a>
				      </h4>
				    </div>
				    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
				      <div class="panel-body">
				        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
				      </div>
				    </div>
				  </div>
				  <div class="panel panel-default">
				    <div class="panel-heading" role="tab" id="headingThree">
				      <h4 class="panel-title">
				        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
				          If I am looking for dimensions, specifications or need technical product information, who I should contact?
				        </a>
				      </h4>
				    </div> -->
				   <!--  <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
				      <div class="panel-body">
				        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
				      </div>
				    </div>
				  </div>
				</div> -->

				
			</div>


		</div>
	</div>

</div>



<%= render :partial => "layouts/footer_no_cta" %>

app/views/distributors/show.html.erb
<div class="container">
  <div class="panel" style="padding: 20px;">
    <div class="alert alert-success text-center" role="alert">You've successfully signed up.</div>
    <h1 class="text-center">We'll contact you as soon as possible</h1>

    <br/>

    <%= link_to raw("<i class=\"fa fa-arrow-left\"></i> Back to Site"), root_url, :class=>"btn btn-default btn-block btn-lg" %>
  </div>

</div>