config/routes.rb
WCSTest::Application.routes.draw do

  resources :roi_surveys , :except => 'index'
  get '/distributors', :to=>'distributors#new'
  resources :distributors

  root to: 'home#index'
  

  get 'calculators/roi', :to=>"roi_surveys#new"

  get "home/index"
  get "home/product"
  get "home/about"
  get "home/distributor_signup"
  get "home/contact"

  

end

app/models/roi_survey.rb
class RoiSurvey < ActiveRecord::Base

	validates_presence_of :store_sq_ft, :haba, :cctv, :walking_svc, :eas_tags_per_month, :total_weekly_sales, :meat_sales_percent, :lpo_hours, :num_pos_terminals, :num_exits, :exit_width_ft,  :eas_effective, :lpo_hours


	def self.square_footages
		square_footages = {
			"Less than 10,000 sq. ft." => 8000,
			"10,000 - 15,000 sq. ft." => 12500,
			"15,000 - 20,000 sq. ft." => 17500,
			"20,000 - 30,000 sq. ft." => 25000,
			"30,000 - 40,000 sq. ft." => 35000,
			"Greater than 40 sq. ft." => 45000		
		}
	end

	def self.weekly_sales
		sales = {
			"Less Than 250,000"  => 250000,
			"250,000 to 350,000"  => 300000,
			"350,000 to 450,000"  => 400000,
			"450,000 to 550,000"  => 500000,
			"550,000 to 650,000"  => 600000,
			"650,000 to 750,000"  => 700000,
			"750,000 to 850,000"  => 800000,
			"Greater Than 850,000"  => 900000
		}
	end

	def self.labels
		sales = {
			"1,000 or less"  => 1000,
			"2,000"   => 2000,
			"3,000"   => 3000,
			"4,000"   => 4000,
			"5,000"   => 5000,
			"6,000"   => 6000,
			"7,000"   => 7000,
			"8,000"   => 8000,
			"9,000"   => 9000,
			"10,000"   => 10000,
			"12,000"   => 12000,
			"14,000"   => 14000,
			"16,000"   => 16000,
			"18,000"   => 18000,
			"20,000"   => 20000

		}
	end


	def self.lpo_hours_select
		sales = {
			"Less Than 5 Hours"  => "1-5 Hours",
			"6-10 Hours"  => "6-10 Hours",
			"11-15 Hours"  => "11-16 Hours",
			"16-20 Hours"  => "16-20 Hours",
			"21-30 Hours"  => "21-30 Hours",
			"31-40 Hours"  => "31-40 Hours",
			"More than 40 Hours"  => "16-20 Hours",
		}
	end

	def self.walking_services
		ws = {"Yes, Internal" => "Yes, Internal",
			  "Yes, External" => "Yes, External",
			  "No" => "No"
			}
	end

	def self.exit_widths
		ew = {"3 feet" => 3, "4 feet" => 4, "6 feet" => 6, "Greater than 6 feet" => 7}
	end

	def self.percentages(increment, start = 0, finish=100)
		percentages = {}
		for i in (start..finish/increment)
			percentages["#{i*increment}%"] = (i*increment)
			
		end
		return percentages
	end

	def self.ints (increment, start = 0, finish=100)

		ints = {}
		for i in (start..finish/increment)
			ints["#{i*increment}"] = (i*increment)
			
		end
		return ints

	end
	def _num_gates_needed
		if self.exit_width_ft > 4

			2*self.num_exits

		else #width <= 4
			1*self.num_exits
		end

	end
end

app/controllers/roi_surveys_controller.rb
class RoiSurveysController < ApplicationController
  before_action :set_roi_survey, only: [:show, :edit, :update, :destroy]

  # GET /roi_surveys
  # GET /roi_surveys.json
  def index
    @roi_surveys = RoiSurvey.all
  end

  # GET /roi_surveys/1
  # GET /roi_surveys/1.json
  def show

  end

  # GET /roi_surveys/new
  def new
    @roi_survey = RoiSurvey.new
    unless params['d'] == 'false'
      @roi_survey.digi = true
    end
  end

  # GET /roi_surveys/1/edit
  def edit
  end

  # POST /roi_surveys
  # POST /roi_surveys.json
  def create
    @roi_survey = RoiSurvey.new(roi_survey_params)

    respond_to do |format|
      if @roi_survey.save
        ContactMailer.survey(@roi_survey).deliver
        format.html { redirect_to @roi_survey, notice: 'Roi survey was successfully created.' }
        format.json { render action: 'show', status: :created, location: @roi_survey }
      else
        format.html { render action: 'new' }
        format.json { render json: @roi_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roi_surveys/1
  # PATCH/PUT /roi_surveys/1.json
  def update
    respond_to do |format|
      if @roi_survey.update(roi_survey_params)
        format.html { redirect_to @roi_survey, notice: 'Roi survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @roi_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roi_surveys/1
  # DELETE /roi_surveys/1.json
  def destroy
    @roi_survey.destroy
    respond_to do |format|
      format.html { redirect_to roi_surveys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roi_survey
      @roi_survey = RoiSurvey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roi_survey_params
      params.require(:roi_survey).permit(:store_sq_ft, :haba, :cctv, :walking_svc, :third_party_inventory, :civil_claim_won, :price_reduction_markdown, :existing_eas, :eas_effective, :lpo_hours, :eas_tags_per_month, :total_weekly_sales, :meat_sales_percent, :num_pos_terminals, :num_exits, :exit_width_ft, :digi)
    end
end

app/helpers/roi_surveys_helper.rb
module RoiSurveysHelper
end

app/views/roi_surveys/_form.html.erb
<%= form_for(@roi_survey) do |f| %>
  <% if @roi_survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roi_survey.errors.count, "error") %> prohibited this calculation:</h2>

      <ul>
      <% @roi_survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <hr/>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :digi, value: @roi_survey.digi %>
  
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">Overall, how effective is your CCTV system?</p>
      </div>
      <div class="col-sm-6 col-lg-4"><table class="table">
          <thead>
            <tr>
              <th colspan="4">1 (Not effective)</th> 
              
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1">10 (Very Effective)</th>
            </tr>
          </thead>
          <tr>
            <% 10.times do |i| %>
              <td><%= f.radio_button :cctv, i+1 %><br/><%= i+1 %></td>
            <% end %>
          </tr>
        </table></div>
    </div>
    
    
  </div>

  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">Overall, how effective is your current EAS system?</p>
      </div>
      <div class="col-sm-6 col-lg-4">
        <table class="table">
          <thead>
            <tr>
              <th colspan="4">1 (Not effective)</th> 
              
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1"></th>
              <th colspan="1">10 (Very Effective)</th>
            </tr>
          </thead>
          <tr>
            <% 10.times do |i| %>
              <td><%= f.radio_button :eas_effective, i %><br/><%= i+1 %></td>
            <% end %>
          </tr>
        </table>
        
      </div>
    </div>
    
    
  </div>

  <hr>
  <div class="field form-group">
    
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        
        <p class="lead">How big is your store?</p>
      </div>
      <div class="col-sm-6 col-lg-4">
        <%= f.collection_select :store_sq_ft, RoiSurvey.square_footages, :last, :first, {}, :class=>"form-control" %>
      </div>
    </div>
    

  </div>
  

  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">Does your store currently employ a walking service.</p>
      </div>
      <div class="col-sm-6 col-lg-4"><%= f.collection_select :walking_svc, RoiSurvey.walking_services, :first, :first , {}, :class=>"form-control"%></div>
    </div>
    
    
  </div>
  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">How many hours per week are Loss Prevention Officers walking?</p>
      </div>
      <div class="col-sm-6 col-lg-4"><%= f.collection_select :lpo_hours, RoiSurvey.lpo_hours_select, :first, :first , {}, :class=>"form-control"%></div>
    </div>
    
    
  </div>
  <hr>

  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">What percentage of sales are HABA (Health and Beauty Accessories)</p>
      </div>
      <div class="col-sm-6 col-lg-4">
        <%= f.collection_select :haba, RoiSurvey.percentages(1,0,25), :last, :first, {}, :class=>"form-control" %>
      </div>
    </div>
    
    
  </div>
  <hr>

  
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">What percentage of sales is meat?</p>
      </div>
      <div class="col-sm-6 col-lg-4"><%= f.collection_select :meat_sales_percent, RoiSurvey.percentages(1,0,35), :last, :first, {}, :class=>"form-control" %></div>
    </div>
    
    
  </div>

  <hr>

  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">What are your total weekly sales?</p>
      </div>
      <div class="col-sm-6 col-lg-4"><%= f.collection_select :total_weekly_sales, RoiSurvey.weekly_sales, :last, :first, {}, :class=>"form-control" %></div>
    </div>
    
    
  </div>
  

  <hr>

  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">Does your store have an existing EAS system in place?</p>
      </div>
      <div class="col-sm-6 col-lg-4">
        <%= f.radio_button :existing_eas, "true" %>&nbsp;<%= label_tag 'roi_survey_existing_eas_true', "Yes" %>
        <%= f.radio_button :existing_eas, "false" %>&nbsp;<%= label_tag 'roi_survey_existing_eas_false', "No" %></div>
    </div>
  </div>
  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">Does a third party count store inventory once per year?</p>
      </div>
      <div class="col-sm-6 col-lg-4">
        <%= f.radio_button :third_party_inventory, "true" %>&nbsp;<%= label_tag 'roi_survey_third_party_inventory_true', "Yes" %>
        <%= f.radio_button :third_party_inventory, "false" %>&nbsp;<%= label_tag 'roi_survey_third_party_inventory_false', "No" %></div>
    </div>
  </div>
  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">Do you have a price reduction program for perishable deli items?</p>
      </div>
      <div class="col-sm-6 col-lg-4">
        <%= f.radio_button :price_reduction_markdown, "true" %>&nbsp;<%= label_tag 'roi_survey_price_reduction_markdown_true', "Yes" %>
        <%= f.radio_button :price_reduction_markdown, "false" %>&nbsp;<%= label_tag 'roi_survey_price_reduction_markdown_false', "No" %></div>
    </div>
  </div>
  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">In the last 5 years, have you had a civil claim allegation whereby you successfully defended yourself? (ie. slip &amp; fall, false arrest, etc)</p>
      </div>
      <div class="col-sm-6 col-lg-4">
        <%= f.radio_button :civil_claim_won, "true" %>&nbsp;<%= label_tag "roi_survey_civil_claim_won_true", "Yes" %>
        <%= f.radio_button :civil_claim_won, "false" %>&nbsp;<%= label_tag "roi_survey_civil_claim_won_false", "No" %></div>
    </div>
  </div>
  
  
  

  <hr>


  
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
      <p class="lead">How many EAS tags do you currently use per month?</p>
      </div>
      <div class="col-sm-6 col-lg-4">
          <%= f.collection_select :eas_tags_per_month, RoiSurvey.labels, :last, :first, {}, :class=>"form-control" %>
        </div>
    </div>
    
    
  </div>


  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8"><p class="lead">How many POS terminals are in your store?</p></div>
      <div class="col-sm-6 col-lg-4">
        <%= f.collection_select :num_pos_terminals, RoiSurvey.ints(1,1,15), :last, :first, {}, :class=>"form-control" %>
      </div>
    </div>
    
    
  </div>
  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8"><p class="lead">How many customer exits?</p></div>
      <div class="col-sm-6 col-lg-4">
        
        <%= f.collection_select :num_exits, RoiSurvey.ints(1,1,10), :last, :first, {}, :class=>"form-control" %>
        
      </div>
    </div>
    
    
  </div>

  <hr>
  <div class="field form-group">
    <div class="row">
      <div class="col-sm-6 col-lg-8">
        <p class="lead">How wide are your customer exits?</p>
      </div>

      <div class="col-sm-6 col-lg-4">
        
          <%= f.collection_select :exit_width_ft, RoiSurvey.exit_widths, :last, :first, {}, :class=>"form-control" %>
      </div>
      
    </div>
    
    
  </div>

  <hr>
  <div class="actions text-center">
    <%= f.submit "Calculate", :class=>"btn btn-lg btn-primary", :style=>"width: 280px" %>
  </div>
  <div class="clearfix"></div>
<% end %>

app/views/roi_surveys/edit.html.erb
<div class="container">
	<h1>Editing ROI Survey</h1>
	<div class="panel"><%= render 'form' %></div>
</div>

app/views/roi_surveys/index.html.erb
<h1>Listing roi_surveys</h1>

<table>
  <thead>
    <tr>
      <th>Store sq ft</th>
      <th>Haba</th>
      <th>Cctv</th>
      <th>Walking svc</th>
      <th>Existing eas</th>
      <th>Eas effective</th>
      <th>Eas tags per month</th>
      <th>Total annual sales</th>
      <th>Meat sales percent</th>
      <th>Num pos terminals</th>
      <th>Num exits</th>
      <th>Num exits 6 feet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @roi_surveys.each do |roi_survey| %>
      <tr>
        <td><%= roi_survey.store_sq_ft %></td>
        <td><%= roi_survey.haba %></td>
        <td><%= roi_survey.cctv %></td>
        <td><%= roi_survey.walking_svc %></td>
        <td><%= roi_survey.existing_eas %></td>
        <td><%= roi_survey.eas_effective %></td>
        <td><%= roi_survey.eas_tags_per_month %></td>
        <td><%= roi_survey.total_annual_sales %></td>
        <td><%= roi_survey.meat_sales_percent %></td>
        <td><%= roi_survey.num_pos_terminals %></td>
        <td><%= roi_survey.num_exits %></td>
        <td><%= roi_survey.num_exits_6_feet %></td>
        <td><%= link_to 'Show', roi_survey %></td>
        <td><%= link_to 'Edit', edit_roi_survey_path(roi_survey) %></td>
        <td><%= link_to 'Destroy', roi_survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roi survey', new_roi_survey_path %>

app/views/roi_surveys/new.html.erb
<% content_for :title do %>
Calculate Return of Investment
<%end%>
<div id="distributors">
	<% if @roi_survey.digi %>

		<header class="digi">
			<div id="background" style="background-image: url(<%= image_url 'store.jpg' %>)"
			  data-0="-ms-transform: translate(0,-100px);-moz-transform: translate(0,-100px);-webkit-transform: translate(0,-100px);transform: translate(0,-100px);" data-200="-ms-transform: translate(0,-50px);-moz-transform: translate(0,-50px);-webkit-transform: translate(0,-50px);transform: translate(0,-50px);"

			></div>
			<div id="map-cover">
			  <h1 class="center">EAS ROI Calculator</h1>
			</div>
			
			<%= image_tag 'digi-logo.png', :class=>"digi-logo" %>

		</header>

	<% else %>

		<header>
			<div id="background" style="background-image: url(<%= image_url 'store.jpg' %>)"
				data-0="-ms-transform: translate(0,-100px);-moz-transform: translate(0,-100px);-webkit-transform: translate(0,-100px);transform: translate(0,-100px);" data-200="-ms-transform: translate(0,-50px);-moz-transform: translate(0,-50px);-webkit-transform: translate(0,-50px);transform: translate(0,-50px);"

			></div>
			<div id="map-cover">
				<h1 class="center">EAS ROI Calculator</h1>
			</div>
			<div class="back-wrap whoosh-left">
				<%= link_to raw("<i class=\"fa fa-arrow-left\"></i>"), root_url, :class=>"btn btn-round btn-default" %>
			</div>
			
		</header>
	<% end %>
</div>

<div class="container">
	
	<div class="panel pad-25">
		<%= render 'form' %>
	</div>

</div>

app/views/roi_surveys/show.html.erb
<% content_for :title do %>
Calculate Return of Investment
<%end%>
<% content_for :title => 'Calculate Return of Investment' %>
<div id="distributors">
  <header>
    <div id="background" style="background-image: url(<%= image_url 'store.jpg' %>)"
      data-0="-ms-transform: translate(0,-100px);-moz-transform: translate(0,-100px);-webkit-transform: translate(0,-100px);transform: translate(0,-100px);" data-200="-ms-transform: translate(0,-50px);-moz-transform: translate(0,-50px);-webkit-transform: translate(0,-50px);transform: translate(0,-50px);"

    ></div>
    <div id="map-cover">
      <h1 class="center">Your Calculation</h1>
    </div>
    <div class="back-wrap whoosh-left">
      <%= link_to raw("<i class=\"fa fa-arrow-left\"></i>"), root_url, :class=>"btn btn-round btn-default" %>
    </div>
    
  </header>
</div>

<% third_party_inventory = (@roi_survey.third_party_inventory ? 1:0) %> 
<% walking_svc = ((@roi_survey.walking_svc == "Yes, Internal" || @roi_survey.walking_svc == "Yes, External") ? 1:0) %> 
<% civil_claim_won = (@roi_survey.civil_claim_won ? 1:0 )%> 
<% prm = (@roi_survey.price_reduction_markdown ? 1:0 )%> 

<% estimated_shrink = (5-(4*(third_party_inventory + walking_svc + civil_claim_won + prm + (@roi_survey.cctv/10) + (@roi_survey.eas_effective/10))/6.0))/100 %>


<% haba_perc     = (0.0+@roi_survey.haba)/100 %><br>
<% meat_perc     = (0.0+@roi_survey.meat_sales_percent)/100 %><br>
<% haba_theft_pc = haba_perc*0.2 %><br>
<% meat_theft_pc = meat_perc*0.2 %><br>

<% theft_shrink_pc    = estimated_shrink*(haba_theft_pc+meat_theft_pc) %>
<% weekly_theft_total = theft_shrink_pc*@roi_survey.total_weekly_sales %>

<div class="container">
  <div class="panel pad-25">
    <!-- <p id="notice"><%= notice %></p> -->

    <div class="panel panel-default">
      <div class="panel-heading text-center">Set Up Cost Comparison</div>
        <table class="table">
          <thead>
            <tr>
              <th>---</th>
              <th>Gates Cost</th>
              <th>Deactivators</th>
              <th>+Installation</th>
              <th>Total</th>
            </tr>
          </thead>

          <tr>
            <th>Competitor Actual</th>
            <td><%= "$#{ comp_gates = @roi_survey._num_gates_needed * 3899 }.00" %></td>
            <td><%= "$#{ comp_deactivators = @roi_survey.num_pos_terminals * 185 }.00" %></td>
            <td><%= "$#{ comp_install = 290+(@roi_survey.num_pos_terminals * 85 ) + (@roi_survey.num_exits * 1995 )}.00" %></td>
            <td><%=  "$#{ comp_gates + comp_deactivators + comp_install}.00" %></td>
          </tr>
          <tr>
            <th>SYNQ Actual</th>
            <td><%= "$#{ sq_gates = @roi_survey._num_gates_needed * 3899}.00" %></td>
            <td><%= "$#{ sq_deactivators = @roi_survey.num_pos_terminals * 185}.00" %></td>
            <td><%= "$#{ sq_install = 290+(@roi_survey.num_pos_terminals * 85) + (@roi_survey._num_gates_needed * 1995)}.00" %></td>
            <td><%=  "$#{ sq_actual = (sq_gates + sq_deactivators + sq_install)}.00" %></td>
          </tr>
        </table>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading text-center">Running Cost Comparison</div>
        <table class="table">
          <thead>
            <tr>
              <th>---</th>
              <th>Label Costs</th>
              <th>Total Labour Costs Per Month</th>
              <th>Monthly Total</th>
              <th>Annual Total</th>

            </tr>
          </thead>

          <tr>
            <th>Competitor Costs/Month </th>
            <td><%= number_to_currency(comp_labels = (@roi_survey.eas_tags_per_month * 0.03)) %></td>
            <td><%= number_to_currency(comp_labour = (@roi_survey.eas_tags_per_month * 0.02 * 25)) %></td>
            <td><%= number_to_currency(comp_monthly_total = (comp_labels + comp_labour)) %></td>
            <td><%= number_to_currency((comp_labels + comp_labour)*12) %></td>

          </tr>
          <tr>
            <th>SYNQ Costs</th>
            <td><%= number_to_currency(sq_labels = @roi_survey.eas_tags_per_month * 0.05) %></td>
            <td><%= "$0.00" %></td>
            <td><%= number_to_currency(sq_monthly_total = sq_labels) %></td>
            <td><%= number_to_currency(sq_labels*12) %></td>

          </tr>
          <tr>
            
          </tr>
          <tr>
            <td colspan="2" align="right"><strong>Estimated Shrink From Theft%:</strong> <%= "#{number_with_precision(theft_shrink_pc*100, :precision=>3)}%" %></td>
            
            <td>&nbsp;</td>
            <td><strong>Weekly Shrink:</strong> <%= number_to_currency weekly_theft_total %></td>
          </tr>
        </table>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading text-center">Savings Comparison</div>
      <table class="table text-center">
        <thead>
          <tr>
            <td></td>
            <th class="text-center">Shrink Reduction Per Week</th>
            <th class="text-center">Weekly EAS Cost</th>
            <th class="text-center">Total Savings (cost)</th>
          </tr>
        </thead>
        <tr>
          <th class="text-right">Competitor EAS</th>
          <td><%= number_to_currency( comp_sr = (0.65 * (@roi_survey.total_weekly_sales * theft_shrink_pc))) %></td>
          <td><%= number_to_currency( comp_monthly_total ) %></td>
          <td><%= number_to_currency( comp_sr - comp_monthly_total ) %></td>
        </tr>
        <tr>
          <th class="text-right">SYNQ EAS</th>
          <td><%= number_to_currency(sq_sr = (0.9 * ((@roi_survey.total_weekly_sales) * theft_shrink_pc ))) %></td>
          <td><%= number_to_currency( sq_monthly_total ) %></td>
          <td><%= number_to_currency( sq_total_savings = (sq_sr - sq_monthly_total) ) %></td>
        </tr>
      </table>
    </div>

        

    <div class="panel panel-default">
      <div class="panel-heading text-center">SYNQ Breakeven</div>
      <table class="table text-center">
        <% breakeven = (sq_actual/sq_total_savings)*12/52 %>
        <% if breakeven > 0 %>
          <tr>
            <th class="text-right">SYNQ One Year Net Cumulative Benefit</th>
            <td><%= number_to_currency( (sq_total_savings * 52) - sq_actual ) %></td>
          </tr>
          <tr>
            <th class="text-right">SYNQ Two Year Net Cumulative Benefit</th>
            <td><%= number_to_currency( (sq_total_savings * 104) - sq_actual ) %></td>
          </tr>
          <tr>
            <th class="text-right">SYNQ Two Three Net Cumulative Benefit</th>
            <td><%= number_to_currency(sq_total_benefit = ( (sq_total_savings * 156) - sq_actual )) %></td>
          </tr>
        </table>
        <!-- BREAKEVEN IS CORRECT - ENSURE NUMBER PRINTED IS > 0 -->
        
          <div class="text-center">
            <strong>Breakeven will occur</strong> in <%= number_with_precision( breakeven, :precision=>1 ) %> months.
          </div>
        <% else %>
          <div class="text-center">
            Breakeven will not occur with shrink reduction alone. 
          </div>
        <% end %>
      
        </table>
    </div>
    
    <div class="text-center">
      <a href="mailto:contact@synqtech.com" class="btn btn-primary btn-lg">Contact SYNQ</a>
    </div>
    <div class="clearfix"></div>
  </div>
</div>