config/routes.rb
WCSTest::Application.routes.draw do

  resources :roi_surveys , :except => 'index'
  get '/distributors', :to=>'distributors#new'
  resources :distributors

  root to: 'home#index'
  

  get 'calculators/roi', :to=>"roi_surveys#new"

  get "home/index"
  get "home/product"
  get "home/about"
  get "home/distributor_signup"
  get "home/contact"

  

end

app/views/layouts/_admin_nav.html.erb
<nav class="navbar navbar-default no-print">

     <a class="navbar-brand" href="#">SYNQ</a>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage... <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Quotes", quotes_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li class="divider"></li>
          <li><a href="#">Sign Out</a></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Create... <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Quote", new_quote_path %></li>
          <li><%= link_to "Product", new_product_path %></li>
          <li class="divider"></li>
          <li><a href="#">Sign Out</a></li>
        </ul>
      </li>
    </ul>
    
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_footer.html.erb
<section class="footer" id="contact">
	
	<div class="call-to-action center">

		<div class="row">


		<%= link_to "Become A Distributor", distributors_path, :class=>"btn btn-cta", :style=>'margin-top: 25px;' %>
		</div>
	</div>	

	<div class="container">
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">

				<!-- Footer Bottom -->
				<div class="row" style="padding-top: 25px;">
						<div class="col-sm-3"></div>
			<div class="col-sm-6">
				<h1 class="center">Contact Us</h1>
				<p class="lead center">Get in touch with SYNQ</p>
				
			</div>
			<div class="col-sm-3"></div>
		</div>
					<!-- Address Block -->
					<div class="col-sm-4 address center-when-small pad-bottom-when-small">
						<strong>SYNQ Technology</strong><br>
							692 Sumas St.<br>
							Victoria, BC
					</div>

					<!-- Social Icons -->
					<div class="col-sm-8 center social">
						<div class="row">
							<div class="col-xs-3 col-sm-2"><a href="mailto:contact@synqtech.com"><i class="fa fa-envelope-o"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-3 col-sm-2"><a href="tel:7784402005"><i class="fa fa-phone"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-3 col-sm-2"><a href="http://www.twitter.com/synqaccess" target="_blank"><i class="fa fa-twitter"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-3 col-sm-2"><a href="http://www.facebook.com/synqaccess" target="_blank"><i class="fa fa-facebook"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-0 col-sm-2"></div>		
						</div>
						
					</div>

				</div>
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
	
</section>

app/views/layouts/_footer_no_cta.html.erb
<section class="footer" id="contact" style="border-top: 20px solid #2287d3;">

	<div class="container">
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
					<div class="row">
						<div class="col-sm-3"></div>
						<div class="col-sm-6">
							<h1 class="center">Contact Us</h1>
							<p class="lead center">Get in touch with SYNQ</p>
							
						</div>
							<div class="col-sm-3"></div>
						</div>
				<!-- Footer Bottom -->
				<div class="row" style="padding-top: 25px;">
					<!-- Address Block -->
					<div class="col-sm-4 address center-when-small pad-bottom-when-small">
						<strong>SYNQ Technology</strong><br>
							692 Sumas St.<br>
							Victoria, BC
					</div>

					<!-- Social Icons -->
					<div class="col-sm-8 center social">
						<div class="row">
							<div class="col-xs-3 col-sm-2"><a href="mailto:contact@synqtech.com"><i class="fa fa-envelope-o"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-3 col-sm-2"><a href="tel:7784402005"><i class="fa fa-phone"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-3 col-sm-2"><a href="http://www.twitter.com/synqaccess" target="_blank"><i class="fa fa-twitter"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-3 col-sm-2"><a href="http://www.facebook.com/synqaccess" target="_blank"><i class="fa fa-facebook"></i><br><span class="hidden-sm hidden-xs"></span></a></div>
							<div class="col-xs-0 col-sm-2"></div>		
						</div>
						
					</div>

				</div>
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
	
</section>

app/views/layouts/_navs.html.erb
<div class="header header-fade hidden-xs">
	<div class="container">
		<div class="brand">
			<%= image_tag 'q-small.png' %>
		</div>
		<nav class="hidden-xs pull-right">

			<ul class="sm-menu">
				
				<li><a href="#about" class="nav-about">About</a></li>
				<li><a href="#products" class="nav-products">Products</a></li>
				<li><a href="#cameras" class="nav-cameras">Cameras</a></li>
				<li><a href="#eas" class="nav-eas">EAS</a></li>
				<li><a href="#contact" class="nav-contact special">Contact Us</a></li>
			</ul>
		</nav>
	</div>
</div>

<div class="header header-secondary header-fade-dark hidden-xs">
	<div class="container">
		<div class="brand">
			<a href="#backtotop"><%= image_tag 'q-small-white.png' %></a>
		</div>
		<nav class="hidden-xs pull-right">

			<ul class="sm-menu">
				<li><a href="#about" class="nav-about">About</a></li>
				<li><a href="#products" class="nav-products">Products</a></li>
				<li><a href="#cameras" class="nav-cameras">Cameras</a></li>
				<li><a href="#eas" class="nav-eas">EAS</a></li>
				<li><a href="#contact" class="nav-contact special">Contact Us</a></li>
			</ul>
		</nav>
	</div>
</div>

<nav class="mobile-nav header-fade-dark visible-xs">
	<div class="nav-top">
		<div class="action-left"></div>
		<div class="logo"><a href="#backtotop"><%= image_tag 'q-small-white.png' %></a></div>
	</div>
	<div class="nav-contents-wrap">
		<ul class="nav-contents">
			<li><a href="#about" class="nav-about">About</a></li>
			<li><a href="#products" class="nav-products">Products</a></li>
			<li><a href="#cameras" class="nav-cameras">Cameras</a></li>
			<li><a href="#eas" class="nav-eas">EAS</a></li>
			<li><a href="#contact" class="nav-contact special">Contact Us</a></li>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SYNQ Technology</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="SYNQ - Access &amp; Security Technology" />
  <meta property="og:site_name" content="SYNQ"/>
  <meta property="og:description" content="SYNQ develops unique solutions and provides consultations for residential and commercial security, retail loss prevention, and liability reduction." />
  <meta property="og:image"content="<%= image_url 'eas/fb.jpg' %>" />
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-56683632-1', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body>

<%= yield %>

</body>
</html>